### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by Algolzw** [YuanfeiHuang/TLSR#1]
Hi, thanks for your interesting work on blind SR!
Since I'd like to cite and compare with your method in my paper, can you provide pre-trained models or result images (on Urban100) for convolutive degradations?

**Comment by Algolzw** [comment]
And I would really appreciate it if you can provide the Quantitative results on Manga109.

**Comment by YuanfeiHuang** [comment]
Thanks for your interest. We have updated the codes and released the pre-trained models in the current version.

**Comment by Algolzw** [comment]
Really nice! Thanks for your help!

**Comment by Algolzw** [comment]
![Screenshot 2022-10-10 at 11 32 15](https://user-images.githubusercontent.com/15884127/194836815-a558922c-0001-4e3f-8ec0-3799c369a2f3.png)

Could you give me some suggestions about this?

**Comment by YuanfeiHuang** [comment]
> ![Screenshot 2022-10-10 at 11 32 15](https://user-images.githubusercontent.com/15884127/194836815-a558922c-0001-4e3f-8ec0-3799c369a2f3.png)
> 
> Could you give me some suggestions about this?

It seems you used the previous codes. You may need to replace them with the updated ones, including main.py, model.py, utils.py, option.py, and the scr/*.py.

**Comment by Algolzw** [comment]
Thanks!
